# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"clock": "weyl_heisenberg.ipynb",
         "shift": "weyl_heisenberg.ipynb",
         "displace": "weyl_heisenberg.ipynb",
         "displacement_operators": "weyl_heisenberg.ipynb",
         "weyl_heisenberg_states": "weyl_heisenberg.ipynb"}

modules = ["weyl_heisenberg.py"]

doc_url = "https://heyredhat.github.io/qbism/qbism/"

git_url = "https://github.com/heyredhat/qbism/tree/{branch}/"

def custom_doc_links(name): return None
