# AUTOGENERATED! DO NOT EDIT! File to edit: weyl_heisenberg.ipynb (unless otherwise specified).

__all__ = ['clock', 'shift', 'displace', 'displacement_operators', 'weyl_heisenberg_states']

# Cell
def clock(d):
    """
    The clock operator for dimension $d$.
    """
    return sum([qt.basis(d, i+1)*qt.basis(d, i).dag()\
                    if i != d-1 else qt.basis(d, 0)*qt.basis(d, i).dag()\
                        for i in range(d) for j in range(d)])/d

# Cell
def shift(d):
    w = np.exp(2*np.pi*1j/d)
    return qt.Qobj(np.diag([w**i for i in range(d)]))

# Cell
def displace(d, a, b):
    Z, X = clock(d), shift(d)
    return (-np.exp(1j*np.pi/d))**(a*b)*X**b*Z**a

# Cell
def displacement_operators(d):
    return dict([((a, b), displace(d, a, b)) for b in range(d) for a in range(d)])

# Cell
def weyl_heisenberg_states(fiducial):
    return [D*fiducial for index, D in displacement_operators(fiducial.shape[0]).items()]